import assets from '../assets/assets';
export const mobil = [
  {
    id: 1,
    nama: 'Civic Type R',
    path: assets.civic,
    merek: 'Honda',
    warna: 'Merah',
    tipe: 'Sedan',
  },
  {
    id: 2,
    nama: 'Innova Venture',
    path: assets.innova,
    merek: 'Toyota',
    warna: 'Putih',
    tipe: 'Mini Bus',
  },
  {
    id: 3,
    nama: 'APV',
    path: assets.apv,
    merek: 'Suzuki',
    warna: 'Hitam',
    tipe: 'Mini Bus',
  },
  {
    id: 4,
    nama: 'M4 Competition',
    path: assets.m4,
    merek: 'BMW',
    warna: 'Biru Tua',
    tipe: 'Sport Car',
  },
  {
    id: 5,
    nama: 'S Class 3000',
    path: assets.sclass,
    merek: 'Mercedes',
    warna: 'Abu-abu',
    tipe: 'Sedan',
  },
  {
    id: 6,
    nama: 'Aventador',
    path: assets.aventador,
    merek: 'Lamborghini',
    warna: 'Kuning',
    tipe: 'Sport Car',
  },
  {
    id: 7,
    nama: 'Almaz',
    path: assets.almaz,
    merek: 'Wuling',
    warna: 'Abu-abu',
    tipe: 'SUV',
  },
  {
    id: 8,
    nama: 'Sigra',
    path: assets.sigra,
    merek: 'Daihatsu',
    warna: 'Hitam',
    tipe: 'Mini Bus',
  },
  {
    id: 9,
    nama: 'Cullinan',
    path: assets.cullinan,
    merek: 'Rolls Royce',
    warna: 'Emas',
    tipe: 'SUV',
  },
  {
    id: 10,
    nama: 'Macan',
    path: assets.macan,
    merek: 'Porsche',
    warna: 'Orange',
    tipe: 'SUV',
  },
  {
    id: 11,
    nama: 'Veyron',
    path: assets.veyron,
    merek: 'Bugatti',
    warna: 'Hitam',
    tipe: 'Sport Car',
  },
  {
    id: 12,
    nama: 'Aventador',
    path: assets.aventador2,
    merek: 'Lamborghini',
    warna: 'Merah',
    tipe: 'Sport Car',
  },
];